import { db } from "./src/firebase/config.js";
import { collection, addDoc, serverTimestamp } from "firebase/firestore";

const testReports = [
  {
    fullName: "Ahmed El Mansouri",
    cin: "AA123456",
    phone: "+212 6 12 34 56 78",
    region: "marrakech",
    type: "flood",
    description: "Flooding near Jemaa el-Fna, water level rising fast.",
    location: { address: "Jemaa el-Fna, Marrakech", lat: 31.6258, lng: -7.9892 },
    status: "pending",
    createdAt: serverTimestamp(),
  },
  {
    fullName: "Fatima Zahra Benali",
    cin: "BE987654",
    phone: "+212 6 98 76 54 32",
    region: "casablanca",
    type: "fire",
    description: "Building fire on Boulevard Zerktouni, 3rd floor.",
    location: { address: "Boulevard Zerktouni, Casablanca", lat: 33.5892, lng: -7.6036 },
    status: "pending",
    createdAt: serverTimestamp(),
  },
  {
    fullName: "Youssef Amrani",
    cin: "CD456789",
    phone: "+212 6 45 67 89 01",
    region: "rabat",
    type: "medical",
    description: "Elderly person collapsed near Hassan Tower.",
    location: { address: "Hassan Tower, Rabat", lat: 34.0242, lng: -6.8222 },
    status: "pending",
    createdAt: serverTimestamp(),
  },
  {
    fullName: "Karim Tazi",
    cin: "EF112233",
    phone: "+212 6 11 22 33 44",
    region: "tangier",
    type: "traffic",
    description: "Major accident on highway A1, 2 vehicles involved.",
    location: { address: "Highway A1, Tangier", lat: 35.7595, lng: -5.8340 },
    status: "pending",
    createdAt: serverTimestamp(),
  },
  {
    fullName: "Sara Idrissi",
    cin: "GH334455",
    phone: "+212 6 33 44 55 66",
    region: "fes",
    type: "infrastructure",
    description: "Bridge crack spotted on Route Nationale 6.",
    location: { address: "Route Nationale 6, Fès", lat: 34.0181, lng: -5.0078 },
    status: "pending",
    createdAt: serverTimestamp(),
  },
  {
    fullName: "Omar Benjelloun",
    cin: "IJ556677",
    phone: "+212 6 55 66 77 88",
    region: "souss",
    type: "flood",
    description: "Oued flooding near Agadir city center.",
    location: { address: "Agadir City Center", lat: 30.4278, lng: -9.5981 },
    status: "pending",
    createdAt: serverTimestamp(),
  },
  {
  fullName: "Hassan Boulahya",
  cin: "AB123987",
  phone: "+212 6 45 23 11 90",
  region: "casablanca",
  type: "fire",
  description: "Small fire reported in an apartment kitchen near Maarif.",
  location: { address: "Maarif, Casablanca", lat: 33.5866, lng: -7.6325 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Nadia El Fassi",
  cin: "BC234876",
  phone: "+212 6 78 55 43 21",
  region: "fes",
  type: "medical",
  description: "Man fainted near Bab Boujloud gate.",
  location: { address: "Bab Boujloud, Fes", lat: 34.0631, lng: -4.9785 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Rachid Loukili",
  cin: "CD345765",
  phone: "+212 6 12 87 65 44",
  region: "tangier",
  type: "traffic",
  description: "Collision between motorcycle and car near Tangier port.",
  location: { address: "Tangier Port", lat: 35.7833, lng: -5.8137 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Salma Amine",
  cin: "DE456654",
  phone: "+212 6 99 54 22 33",
  region: "rabat",
  type: "infrastructure",
  description: "Streetlight pole fell after strong wind.",
  location: { address: "Agdal, Rabat", lat: 34.0026, lng: -6.8498 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Yassine Belkadi",
  cin: "EF567543",
  phone: "+212 6 55 21 77 11",
  region: "marrakech",
  type: "flood",
  description: "Heavy rain flooding streets near Gueliz district.",
  location: { address: "Gueliz, Marrakech", lat: 31.6295, lng: -8.0106 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Khadija Ziani",
  cin: "FG678432",
  phone: "+212 6 34 90 56 88",
  region: "meknes",
  type: "medical",
  description: "Child injured while playing in park.",
  location: { address: "Lahdim Square, Meknes", lat: 33.8935, lng: -5.5473 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Mehdi Oulhaj",
  cin: "GH789321",
  phone: "+212 6 21 66 11 09",
  region: "agadir",
  type: "traffic",
  description: "Bus broke down blocking traffic near Marina.",
  location: { address: "Agadir Marina", lat: 30.4202, lng: -9.6030 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Samira Talbi",
  cin: "HI890210",
  phone: "+212 6 73 44 11 22",
  region: "oujda",
  type: "fire",
  description: "Smoke seen coming from warehouse.",
  location: { address: "Industrial Zone, Oujda", lat: 34.6814, lng: -1.9086 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Younes Dlimi",
  cin: "IJ901234",
  phone: "+212 6 17 99 23 44",
  region: "tetouan",
  type: "flood",
  description: "Water overflowing near Martil river.",
  location: { address: "Martil River, Tetouan", lat: 35.5711, lng: -5.3724 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Oumaima Cherkaoui",
  cin: "JK112233",
  phone: "+212 6 61 44 88 55",
  region: "casablanca",
  type: "medical",
  description: "Pregnant woman needs urgent help near tram station.",
  location: { address: "Sidi Abderrahmane, Casablanca", lat: 33.5731, lng: -7.6873 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Hamza Idrissi",
  cin: "KL223344",
  phone: "+212 6 22 88 44 66",
  region: "rabat",
  type: "traffic",
  description: "Two cars collided near Rabat Ville station.",
  location: { address: "Rabat Ville Station", lat: 34.0185, lng: -6.8356 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Amina El Khatib",
  cin: "LM334455",
  phone: "+212 6 66 11 99 77",
  region: "fes",
  type: "infrastructure",
  description: "Large pothole causing traffic disruption.",
  location: { address: "Avenue Hassan II, Fes", lat: 34.0400, lng: -5.0003 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Zakaria Haddad",
  cin: "MN445566",
  phone: "+212 6 71 33 66 11",
  region: "marrakech",
  type: "fire",
  description: "Trash container fire spreading smoke.",
  location: { address: "Medina, Marrakech", lat: 31.6295, lng: -7.9811 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Noureddine Bennis",
  cin: "NO556677",
  phone: "+212 6 54 12 77 88",
  region: "tangier",
  type: "medical",
  description: "Tourist injured after falling on stairs.",
  location: { address: "Kasbah, Tangier", lat: 35.7890, lng: -5.8125 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Imane Saidi",
  cin: "OP667788",
  phone: "+212 6 91 32 44 55",
  region: "agadir",
  type: "flood",
  description: "Storm water flooding parking area.",
  location: { address: "Souk El Had, Agadir", lat: 30.4208, lng: -9.5833 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Bilal Achouri",
  cin: "PQ778899",
  phone: "+212 6 28 90 12 11",
  region: "meknes",
  type: "traffic",
  description: "Truck accident blocking roundabout.",
  location: { address: "Meknes Roundabout", lat: 33.8892, lng: -5.5519 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Sofia Belhaj",
  cin: "QR889900",
  phone: "+212 6 33 22 77 66",
  region: "rabat",
  type: "fire",
  description: "Electrical fire reported in office building.",
  location: { address: "Hay Riad, Rabat", lat: 33.9700, lng: -6.8670 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Othmane El Alami",
  cin: "RS990011",
  phone: "+212 6 81 66 11 22",
  region: "casablanca",
  type: "infrastructure",
  description: "Water pipe burst flooding sidewalk.",
  location: { address: "Ain Diab, Casablanca", lat: 33.5987, lng: -7.6878 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Latifa Kabbaj",
  cin: "ST101112",
  phone: "+212 6 59 11 33 44",
  region: "tetouan",
  type: "medical",
  description: "Elderly man having breathing difficulty.",
  location: { address: "Tetouan Medina", lat: 35.5889, lng: -5.3626 },
  status: "pending",
  createdAt: serverTimestamp(),
},
{
  fullName: "Anas Mouline",
  cin: "TU121314",
  phone: "+212 6 40 77 55 22",
  region: "oujda",
  type: "traffic",
  description: "Minor accident near university entrance.",
  location: { address: "Mohammed I University, Oujda", lat: 34.6536, lng: -1.8973 },
  status: "pending",
  createdAt: serverTimestamp(),
}
];

const seed = async () => {
  for (const report of testReports) {
    const doc = await addDoc(collection(db, "reports"), report);
    console.log(`Added: ${report.type} — ${report.fullName} (${doc.id})`);
  }
  console.log("Seeding complete.");
};

seed();